# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ccdb_sdk.api.trends_api import TrendsApi


class TestTrendsApi(unittest.TestCase):
    """TrendsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrendsApi()

    def tearDown(self) -> None:
        pass

    def test_trends_get(self) -> None:
        """Test case for trends_get

        List trends
        """
        pass


if __name__ == '__main__':
    unittest.main()
