# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hits_total import HitsTotal

class TestHitsTotal(unittest.TestCase):
    """HitsTotal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HitsTotal:
        """Test HitsTotal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HitsTotal`
        """
        model = HitsTotal()
        if include_optional:
            return HitsTotal(
                value = 56,
                relation = ''
            )
        else:
            return HitsTotal(
        )
        """

    def testHitsTotal(self):
        """Test HitsTotal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
