# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ccdb_sdk.api.complaints_api import ComplaintsApi


class TestComplaintsApi(unittest.TestCase):
    """ComplaintsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComplaintsApi()

    def tearDown(self) -> None:
        pass

    def test_complaint_id_get(self) -> None:
        """Test case for complaint_id_get

        Find consumer complaint by ID
        """
        pass

    def test_geo_states_get(self) -> None:
        """Test case for geo_states_get

        Get the state-by-state information
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Search consumer complaints
        """
        pass


if __name__ == '__main__':
    unittest.main()
