# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ccdb_sdk.models.multi_level_aggregation_field import MultiLevelAggregationField

class TestMultiLevelAggregationField(unittest.TestCase):
    """MultiLevelAggregationField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiLevelAggregationField:
        """Test MultiLevelAggregationField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiLevelAggregationField`
        """
        model = MultiLevelAggregationField()
        if include_optional:
            return MultiLevelAggregationField(
                buckets = [
                    ccdb_sdk.models.multi_level_bucket.MultiLevelBucket(
                        doc_count = 56, 
                        field/raw = ccdb_sdk.models.multi_level_bucket_field_raw.MultiLevelBucket_field_raw(), 
                        key = '', )
                    ],
                doc_count_error_upper_bound = 56,
                sum_other_doc_count = 56
            )
        else:
            return MultiLevelAggregationField(
        )
        """

    def testMultiLevelAggregationField(self):
        """Test MultiLevelAggregationField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
