# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.typeahead_api import TypeaheadApi


class TestTypeaheadApi(unittest.TestCase):
    """TypeaheadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TypeaheadApi()

    def tearDown(self) -> None:
        pass

    def test_suggest_company_get(self) -> None:
        """Test case for suggest_company_get

        Suggest possible companies
        """
        pass

    def test_suggest_get(self) -> None:
        """Test case for suggest_get

        Suggest possible searches
        """
        pass

    def test_suggest_zip_get(self) -> None:
        """Test case for suggest_zip_get

        Suggest possible zip codes
        """
        pass


if __name__ == '__main__':
    unittest.main()
