# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from openapi_client.models.trends_result import TrendsResult

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class TrendsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def trends_get(
        self,
        lens: Annotated[StrictStr, Field(description="The data lens through which to view complaint trends over time.")],
        trend_interval: Annotated[StrictStr, Field(description="The interval of time to use for trends aggregations histograms. When using day intervals, we recommend querying for date_received_min / max periods of less than one year.")],
        search_term: Annotated[Optional[StrictStr], Field(description="Return results containing specific term")] = None,
        var_field: Annotated[Optional[StrictStr], Field(description="If the parameter \"search_term\" has a value, use \"field\" to specify which field is searched. If not specified, \"complaint_what_happened\" will be searched.")] = None,
        company: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these companies")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        focus: Annotated[Optional[List[StrictStr]], Field(description="The name of the product or company on which to focus charts for products and issues")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        sub_lens: Annotated[Optional[StrictStr], Field(description="The sub-lens through which to view complaint trends over time.")] = None,
        sub_lens_depth: Annotated[Optional[Annotated[int, Field(le=10000000, strict=True, ge=5)]], Field(description="The top X trend sub aggregations will be returned, where X is the supplied sub_lens_depth.")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        trend_depth: Annotated[Optional[Annotated[int, Field(le=10000000, strict=True, ge=5)]], Field(description="The top X trend aggregations will be returned, where X is the supplied trend_depth.")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TrendsResult:
        """List trends

        Return specific aggregations for a search

        :param lens: The data lens through which to view complaint trends over time. (required)
        :type lens: str
        :param trend_interval: The interval of time to use for trends aggregations histograms. When using day intervals, we recommend querying for date_received_min / max periods of less than one year. (required)
        :type trend_interval: str
        :param search_term: Return results containing specific term
        :type search_term: str
        :param var_field: If the parameter \"search_term\" has a value, use \"field\" to specify which field is searched. If not specified, \"complaint_what_happened\" will be searched.
        :type var_field: str
        :param company: Filter the results to only return these companies
        :type company: List[str]
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param focus: The name of the product or company on which to focus charts for products and issues
        :type focus: List[str]
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param sub_lens: The sub-lens through which to view complaint trends over time.
        :type sub_lens: str
        :param sub_lens_depth: The top X trend sub aggregations will be returned, where X is the supplied sub_lens_depth.
        :type sub_lens_depth: int
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param trend_depth: The top X trend aggregations will be returned, where X is the supplied trend_depth.
        :type trend_depth: int
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._trends_get_serialize(
            lens=lens,
            trend_interval=trend_interval,
            search_term=search_term,
            var_field=var_field,
            company=company,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            focus=focus,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            sub_lens=sub_lens,
            sub_lens_depth=sub_lens_depth,
            tags=tags,
            timely=timely,
            trend_depth=trend_depth,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TrendsResult",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def trends_get_with_http_info(
        self,
        lens: Annotated[StrictStr, Field(description="The data lens through which to view complaint trends over time.")],
        trend_interval: Annotated[StrictStr, Field(description="The interval of time to use for trends aggregations histograms. When using day intervals, we recommend querying for date_received_min / max periods of less than one year.")],
        search_term: Annotated[Optional[StrictStr], Field(description="Return results containing specific term")] = None,
        var_field: Annotated[Optional[StrictStr], Field(description="If the parameter \"search_term\" has a value, use \"field\" to specify which field is searched. If not specified, \"complaint_what_happened\" will be searched.")] = None,
        company: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these companies")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        focus: Annotated[Optional[List[StrictStr]], Field(description="The name of the product or company on which to focus charts for products and issues")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        sub_lens: Annotated[Optional[StrictStr], Field(description="The sub-lens through which to view complaint trends over time.")] = None,
        sub_lens_depth: Annotated[Optional[Annotated[int, Field(le=10000000, strict=True, ge=5)]], Field(description="The top X trend sub aggregations will be returned, where X is the supplied sub_lens_depth.")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        trend_depth: Annotated[Optional[Annotated[int, Field(le=10000000, strict=True, ge=5)]], Field(description="The top X trend aggregations will be returned, where X is the supplied trend_depth.")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TrendsResult]:
        """List trends

        Return specific aggregations for a search

        :param lens: The data lens through which to view complaint trends over time. (required)
        :type lens: str
        :param trend_interval: The interval of time to use for trends aggregations histograms. When using day intervals, we recommend querying for date_received_min / max periods of less than one year. (required)
        :type trend_interval: str
        :param search_term: Return results containing specific term
        :type search_term: str
        :param var_field: If the parameter \"search_term\" has a value, use \"field\" to specify which field is searched. If not specified, \"complaint_what_happened\" will be searched.
        :type var_field: str
        :param company: Filter the results to only return these companies
        :type company: List[str]
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param focus: The name of the product or company on which to focus charts for products and issues
        :type focus: List[str]
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param sub_lens: The sub-lens through which to view complaint trends over time.
        :type sub_lens: str
        :param sub_lens_depth: The top X trend sub aggregations will be returned, where X is the supplied sub_lens_depth.
        :type sub_lens_depth: int
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param trend_depth: The top X trend aggregations will be returned, where X is the supplied trend_depth.
        :type trend_depth: int
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._trends_get_serialize(
            lens=lens,
            trend_interval=trend_interval,
            search_term=search_term,
            var_field=var_field,
            company=company,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            focus=focus,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            sub_lens=sub_lens,
            sub_lens_depth=sub_lens_depth,
            tags=tags,
            timely=timely,
            trend_depth=trend_depth,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TrendsResult",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def trends_get_without_preload_content(
        self,
        lens: Annotated[StrictStr, Field(description="The data lens through which to view complaint trends over time.")],
        trend_interval: Annotated[StrictStr, Field(description="The interval of time to use for trends aggregations histograms. When using day intervals, we recommend querying for date_received_min / max periods of less than one year.")],
        search_term: Annotated[Optional[StrictStr], Field(description="Return results containing specific term")] = None,
        var_field: Annotated[Optional[StrictStr], Field(description="If the parameter \"search_term\" has a value, use \"field\" to specify which field is searched. If not specified, \"complaint_what_happened\" will be searched.")] = None,
        company: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these companies")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        focus: Annotated[Optional[List[StrictStr]], Field(description="The name of the product or company on which to focus charts for products and issues")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        sub_lens: Annotated[Optional[StrictStr], Field(description="The sub-lens through which to view complaint trends over time.")] = None,
        sub_lens_depth: Annotated[Optional[Annotated[int, Field(le=10000000, strict=True, ge=5)]], Field(description="The top X trend sub aggregations will be returned, where X is the supplied sub_lens_depth.")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        trend_depth: Annotated[Optional[Annotated[int, Field(le=10000000, strict=True, ge=5)]], Field(description="The top X trend aggregations will be returned, where X is the supplied trend_depth.")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List trends

        Return specific aggregations for a search

        :param lens: The data lens through which to view complaint trends over time. (required)
        :type lens: str
        :param trend_interval: The interval of time to use for trends aggregations histograms. When using day intervals, we recommend querying for date_received_min / max periods of less than one year. (required)
        :type trend_interval: str
        :param search_term: Return results containing specific term
        :type search_term: str
        :param var_field: If the parameter \"search_term\" has a value, use \"field\" to specify which field is searched. If not specified, \"complaint_what_happened\" will be searched.
        :type var_field: str
        :param company: Filter the results to only return these companies
        :type company: List[str]
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param focus: The name of the product or company on which to focus charts for products and issues
        :type focus: List[str]
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param sub_lens: The sub-lens through which to view complaint trends over time.
        :type sub_lens: str
        :param sub_lens_depth: The top X trend sub aggregations will be returned, where X is the supplied sub_lens_depth.
        :type sub_lens_depth: int
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param trend_depth: The top X trend aggregations will be returned, where X is the supplied trend_depth.
        :type trend_depth: int
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._trends_get_serialize(
            lens=lens,
            trend_interval=trend_interval,
            search_term=search_term,
            var_field=var_field,
            company=company,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            focus=focus,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            sub_lens=sub_lens,
            sub_lens_depth=sub_lens_depth,
            tags=tags,
            timely=timely,
            trend_depth=trend_depth,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TrendsResult",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _trends_get_serialize(
        self,
        lens,
        trend_interval,
        search_term,
        var_field,
        company,
        company_public_response,
        company_received_max,
        company_received_min,
        company_response,
        consumer_consent_provided,
        consumer_disputed,
        date_received_max,
        date_received_min,
        focus,
        has_narrative,
        issue,
        product,
        state,
        submitted_via,
        sub_lens,
        sub_lens_depth,
        tags,
        timely,
        trend_depth,
        zip_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'company': 'multi',
            'company_public_response': 'multi',
            'company_response': 'multi',
            'consumer_consent_provided': 'multi',
            'consumer_disputed': 'multi',
            'focus': 'multi',
            'has_narrative': 'multi',
            'issue': 'multi',
            'product': 'multi',
            'state': 'multi',
            'submitted_via': 'multi',
            'tags': 'multi',
            'timely': 'multi',
            'zip_code': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if search_term is not None:
            
            _query_params.append(('search_term', search_term))
            
        if var_field is not None:
            
            _query_params.append(('field', var_field))
            
        if company is not None:
            
            _query_params.append(('company', company))
            
        if company_public_response is not None:
            
            _query_params.append(('company_public_response', company_public_response))
            
        if company_received_max is not None:
            if isinstance(company_received_max, date):
                _query_params.append(
                    (
                        'company_received_max',
                        company_received_max.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('company_received_max', company_received_max))
            
        if company_received_min is not None:
            if isinstance(company_received_min, date):
                _query_params.append(
                    (
                        'company_received_min',
                        company_received_min.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('company_received_min', company_received_min))
            
        if company_response is not None:
            
            _query_params.append(('company_response', company_response))
            
        if consumer_consent_provided is not None:
            
            _query_params.append(('consumer_consent_provided', consumer_consent_provided))
            
        if consumer_disputed is not None:
            
            _query_params.append(('consumer_disputed', consumer_disputed))
            
        if date_received_max is not None:
            if isinstance(date_received_max, date):
                _query_params.append(
                    (
                        'date_received_max',
                        date_received_max.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date_received_max', date_received_max))
            
        if date_received_min is not None:
            if isinstance(date_received_min, date):
                _query_params.append(
                    (
                        'date_received_min',
                        date_received_min.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date_received_min', date_received_min))
            
        if focus is not None:
            
            _query_params.append(('focus', focus))
            
        if has_narrative is not None:
            
            _query_params.append(('has_narrative', has_narrative))
            
        if issue is not None:
            
            _query_params.append(('issue', issue))
            
        if lens is not None:
            
            _query_params.append(('lens', lens))
            
        if product is not None:
            
            _query_params.append(('product', product))
            
        if state is not None:
            
            _query_params.append(('state', state))
            
        if submitted_via is not None:
            
            _query_params.append(('submitted_via', submitted_via))
            
        if sub_lens is not None:
            
            _query_params.append(('sub_lens', sub_lens))
            
        if sub_lens_depth is not None:
            
            _query_params.append(('sub_lens_depth', sub_lens_depth))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if timely is not None:
            
            _query_params.append(('timely', timely))
            
        if trend_depth is not None:
            
            _query_params.append(('trend_depth', trend_depth))
            
        if trend_interval is not None:
            
            _query_params.append(('trend_interval', trend_interval))
            
        if zip_code is not None:
            
            _query_params.append(('zip_code', zip_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/csv'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/trends',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


