# coding: utf-8

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class TypeaheadApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def suggest_company_get(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Suggest possible companies

        Provide a list of companies that match the input text

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_company_get_serialize(
            text=text,
            size=size,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            tags=tags,
            timely=timely,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def suggest_company_get_with_http_info(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Suggest possible companies

        Provide a list of companies that match the input text

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_company_get_serialize(
            text=text,
            size=size,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            tags=tags,
            timely=timely,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def suggest_company_get_without_preload_content(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Suggest possible companies

        Provide a list of companies that match the input text

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_company_get_serialize(
            text=text,
            size=size,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            tags=tags,
            timely=timely,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _suggest_company_get_serialize(
        self,
        text,
        size,
        company_public_response,
        company_received_max,
        company_received_min,
        company_response,
        consumer_consent_provided,
        consumer_disputed,
        date_received_max,
        date_received_min,
        has_narrative,
        issue,
        product,
        state,
        submitted_via,
        tags,
        timely,
        zip_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'company_public_response': 'multi',
            'company_response': 'multi',
            'consumer_consent_provided': 'multi',
            'consumer_disputed': 'multi',
            'has_narrative': 'multi',
            'issue': 'multi',
            'product': 'multi',
            'state': 'multi',
            'submitted_via': 'multi',
            'tags': 'multi',
            'timely': 'multi',
            'zip_code': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if text is not None:
            
            _query_params.append(('text', text))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        if company_public_response is not None:
            
            _query_params.append(('company_public_response', company_public_response))
            
        if company_received_max is not None:
            if isinstance(company_received_max, date):
                _query_params.append(
                    (
                        'company_received_max',
                        company_received_max.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('company_received_max', company_received_max))
            
        if company_received_min is not None:
            if isinstance(company_received_min, date):
                _query_params.append(
                    (
                        'company_received_min',
                        company_received_min.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('company_received_min', company_received_min))
            
        if company_response is not None:
            
            _query_params.append(('company_response', company_response))
            
        if consumer_consent_provided is not None:
            
            _query_params.append(('consumer_consent_provided', consumer_consent_provided))
            
        if consumer_disputed is not None:
            
            _query_params.append(('consumer_disputed', consumer_disputed))
            
        if date_received_max is not None:
            if isinstance(date_received_max, date):
                _query_params.append(
                    (
                        'date_received_max',
                        date_received_max.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date_received_max', date_received_max))
            
        if date_received_min is not None:
            if isinstance(date_received_min, date):
                _query_params.append(
                    (
                        'date_received_min',
                        date_received_min.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date_received_min', date_received_min))
            
        if has_narrative is not None:
            
            _query_params.append(('has_narrative', has_narrative))
            
        if issue is not None:
            
            _query_params.append(('issue', issue))
            
        if product is not None:
            
            _query_params.append(('product', product))
            
        if state is not None:
            
            _query_params.append(('state', state))
            
        if submitted_via is not None:
            
            _query_params.append(('submitted_via', submitted_via))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if timely is not None:
            
            _query_params.append(('timely', timely))
            
        if zip_code is not None:
            
            _query_params.append(('zip_code', zip_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/_suggest_company',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def suggest_get(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Suggest possible searches

        The endpoint for the main search box in the UI

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_get_serialize(
            text=text,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def suggest_get_with_http_info(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Suggest possible searches

        The endpoint for the main search box in the UI

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_get_serialize(
            text=text,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def suggest_get_without_preload_content(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Suggest possible searches

        The endpoint for the main search box in the UI

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_get_serialize(
            text=text,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _suggest_get_serialize(
        self,
        text,
        size,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if size is not None:
            
            _query_params.append(('size', size))
            
        if text is not None:
            
            _query_params.append(('text', text))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/_suggest',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def suggest_zip_get(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Suggest possible zip codes

        Provide a list of zip codes that match the input text

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_zip_get_serialize(
            text=text,
            size=size,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            tags=tags,
            timely=timely,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def suggest_zip_get_with_http_info(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Suggest possible zip codes

        Provide a list of zip codes that match the input text

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_zip_get_serialize(
            text=text,
            size=size,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            tags=tags,
            timely=timely,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def suggest_zip_get_without_preload_content(
        self,
        text: Annotated[StrictStr, Field(description="text to use for suggestions")],
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Limit the size of the results")] = None,
        company_public_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of public response by the company")] = None,
        company_received_max: Annotated[Optional[date], Field(description="Return results with date < company_received_max (i.e. 2017-03-04)")] = None,
        company_received_min: Annotated[Optional[date], Field(description="Return results with date >= company_received_min (i.e. 2017-03-04)")] = None,
        company_response: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of response by the company")] = None,
        consumer_consent_provided: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of consent consumer provided")] = None,
        consumer_disputed: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of consumer disputed, i.e. yes, no")] = None,
        date_received_max: Annotated[Optional[date], Field(description="Return results with date < date_received_max (i.e. 2017-03-04)")] = None,
        date_received_min: Annotated[Optional[date], Field(description="Return results with date >= date_received_min (i.e. 2017-03-04)")] = None,
        has_narrative: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no")] = None,
        issue: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan")] = None,
        product: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage")] = None,
        state: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these states (use abbreviation, i.e. CA, VA)")] = None,
        submitted_via: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of way consumers submitted their complaints")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these types of tag")] = None,
        timely: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to show whether a response was timely")] = None,
        zip_code: Annotated[Optional[List[StrictStr]], Field(description="Filter the results to only return these zip codes")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Suggest possible zip codes

        Provide a list of zip codes that match the input text

        :param text: text to use for suggestions (required)
        :type text: str
        :param size: Limit the size of the results
        :type size: int
        :param company_public_response: Filter the results to only return these types of public response by the company
        :type company_public_response: List[str]
        :param company_received_max: Return results with date < company_received_max (i.e. 2017-03-04)
        :type company_received_max: date
        :param company_received_min: Return results with date >= company_received_min (i.e. 2017-03-04)
        :type company_received_min: date
        :param company_response: Filter the results to only return these types of response by the company
        :type company_response: List[str]
        :param consumer_consent_provided: Filter the results to only return these types of consent consumer provided
        :type consumer_consent_provided: List[str]
        :param consumer_disputed: Filter the results to only return the specified state of consumer disputed, i.e. yes, no
        :type consumer_disputed: List[str]
        :param date_received_max: Return results with date < date_received_max (i.e. 2017-03-04)
        :type date_received_max: date
        :param date_received_min: Return results with date >= date_received_min (i.e. 2017-03-04)
        :type date_received_min: date
        :param has_narrative: Filter the results to only return the specified state of whether it has narrative in the complaint or not, i.e. yes, no
        :type has_narrative: List[str]
        :param issue: Filter the results to only return these types of issue and subissue, i.e. product-only: Getting a Loan, subproduct needs to include product, separated by '•', Getting a Loan•Can't qualify for a loan
        :type issue: List[str]
        :param product: Filter the results to only return these types of product and subproduct, i.e. product-only: Mortgage, subproduct needs to include product, separated by '•', Mortgage•FHA mortgage
        :type product: List[str]
        :param state: Filter the results to only return these states (use abbreviation, i.e. CA, VA)
        :type state: List[str]
        :param submitted_via: Filter the results to only return these types of way consumers submitted their complaints
        :type submitted_via: List[str]
        :param tags: Filter the results to only return these types of tag
        :type tags: List[str]
        :param timely: Filter the results to show whether a response was timely
        :type timely: List[str]
        :param zip_code: Filter the results to only return these zip codes
        :type zip_code: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._suggest_zip_get_serialize(
            text=text,
            size=size,
            company_public_response=company_public_response,
            company_received_max=company_received_max,
            company_received_min=company_received_min,
            company_response=company_response,
            consumer_consent_provided=consumer_consent_provided,
            consumer_disputed=consumer_disputed,
            date_received_max=date_received_max,
            date_received_min=date_received_min,
            has_narrative=has_narrative,
            issue=issue,
            product=product,
            state=state,
            submitted_via=submitted_via,
            tags=tags,
            timely=timely,
            zip_code=zip_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '400': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _suggest_zip_get_serialize(
        self,
        text,
        size,
        company_public_response,
        company_received_max,
        company_received_min,
        company_response,
        consumer_consent_provided,
        consumer_disputed,
        date_received_max,
        date_received_min,
        has_narrative,
        issue,
        product,
        state,
        submitted_via,
        tags,
        timely,
        zip_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'company_public_response': 'multi',
            'company_response': 'multi',
            'consumer_consent_provided': 'multi',
            'consumer_disputed': 'multi',
            'has_narrative': 'multi',
            'issue': 'multi',
            'product': 'multi',
            'state': 'multi',
            'submitted_via': 'multi',
            'tags': 'multi',
            'timely': 'multi',
            'zip_code': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if text is not None:
            
            _query_params.append(('text', text))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        if company_public_response is not None:
            
            _query_params.append(('company_public_response', company_public_response))
            
        if company_received_max is not None:
            if isinstance(company_received_max, date):
                _query_params.append(
                    (
                        'company_received_max',
                        company_received_max.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('company_received_max', company_received_max))
            
        if company_received_min is not None:
            if isinstance(company_received_min, date):
                _query_params.append(
                    (
                        'company_received_min',
                        company_received_min.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('company_received_min', company_received_min))
            
        if company_response is not None:
            
            _query_params.append(('company_response', company_response))
            
        if consumer_consent_provided is not None:
            
            _query_params.append(('consumer_consent_provided', consumer_consent_provided))
            
        if consumer_disputed is not None:
            
            _query_params.append(('consumer_disputed', consumer_disputed))
            
        if date_received_max is not None:
            if isinstance(date_received_max, date):
                _query_params.append(
                    (
                        'date_received_max',
                        date_received_max.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date_received_max', date_received_max))
            
        if date_received_min is not None:
            if isinstance(date_received_min, date):
                _query_params.append(
                    (
                        'date_received_min',
                        date_received_min.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date_received_min', date_received_min))
            
        if has_narrative is not None:
            
            _query_params.append(('has_narrative', has_narrative))
            
        if issue is not None:
            
            _query_params.append(('issue', issue))
            
        if product is not None:
            
            _query_params.append(('product', product))
            
        if state is not None:
            
            _query_params.append(('state', state))
            
        if submitted_via is not None:
            
            _query_params.append(('submitted_via', submitted_via))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if timely is not None:
            
            _query_params.append(('timely', timely))
            
        if zip_code is not None:
            
            _query_params.append(('zip_code', zip_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/_suggest_zip',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


