# coding: utf-8

# flake8: noqa
"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from ccdb_sdk.models.aggregation import Aggregation
    from ccdb_sdk.models.aggregation_date import AggregationDate
    from ccdb_sdk.models.aggregation_field import AggregationField
    from ccdb_sdk.models.bucket import Bucket
    from ccdb_sdk.models.complaint import Complaint
    from ccdb_sdk.models.hit import Hit
    from ccdb_sdk.models.hits import Hits
    from ccdb_sdk.models.hits_total import HitsTotal
    from ccdb_sdk.models.meta import Meta
    from ccdb_sdk.models.multi_level_aggregation import MultiLevelAggregation
    from ccdb_sdk.models.multi_level_aggregation_field import MultiLevelAggregationField
    from ccdb_sdk.models.multi_level_bucket import MultiLevelBucket
    from ccdb_sdk.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw
    from ccdb_sdk.models.search_result import SearchResult
    from ccdb_sdk.models.search_result_aggregations import SearchResultAggregations
    from ccdb_sdk.models.states_result import StatesResult
    from ccdb_sdk.models.states_result_aggregations import StatesResultAggregations
    from ccdb_sdk.models.trends_result import TrendsResult
    from ccdb_sdk.models.trends_result_aggregations import TrendsResultAggregations
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from ccdb_sdk.models.aggregation import Aggregation
from ccdb_sdk.models.aggregation_date import AggregationDate
from ccdb_sdk.models.aggregation_field import AggregationField
from ccdb_sdk.models.bucket import Bucket
from ccdb_sdk.models.complaint import Complaint
from ccdb_sdk.models.hit import Hit
from ccdb_sdk.models.hits import Hits
from ccdb_sdk.models.hits_total import HitsTotal
from ccdb_sdk.models.meta import Meta
from ccdb_sdk.models.multi_level_aggregation import MultiLevelAggregation
from ccdb_sdk.models.multi_level_aggregation_field import MultiLevelAggregationField
from ccdb_sdk.models.multi_level_bucket import MultiLevelBucket
from ccdb_sdk.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw
from ccdb_sdk.models.search_result import SearchResult
from ccdb_sdk.models.search_result_aggregations import SearchResultAggregations
from ccdb_sdk.models.states_result import StatesResult
from ccdb_sdk.models.states_result_aggregations import StatesResultAggregations
from ccdb_sdk.models.trends_result import TrendsResult
from ccdb_sdk.models.trends_result_aggregations import TrendsResultAggregations

""",
            name=__name__,
            doc=__doc__,
        )
    )
