# coding: utf-8

# flake8: noqa
"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from openapi_client.models.aggregation import Aggregation
    from openapi_client.models.aggregation_date import AggregationDate
    from openapi_client.models.aggregation_field import AggregationField
    from openapi_client.models.bucket import Bucket
    from openapi_client.models.complaint import Complaint
    from openapi_client.models.hit import Hit
    from openapi_client.models.hits import Hits
    from openapi_client.models.hits_total import HitsTotal
    from openapi_client.models.meta import Meta
    from openapi_client.models.multi_level_aggregation import MultiLevelAggregation
    from openapi_client.models.multi_level_aggregation_field import MultiLevelAggregationField
    from openapi_client.models.multi_level_bucket import MultiLevelBucket
    from openapi_client.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw
    from openapi_client.models.search_result import SearchResult
    from openapi_client.models.search_result_aggregations import SearchResultAggregations
    from openapi_client.models.states_result import StatesResult
    from openapi_client.models.states_result_aggregations import StatesResultAggregations
    from openapi_client.models.trends_result import TrendsResult
    from openapi_client.models.trends_result_aggregations import TrendsResultAggregations
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from openapi_client.models.aggregation import Aggregation
from openapi_client.models.aggregation_date import AggregationDate
from openapi_client.models.aggregation_field import AggregationField
from openapi_client.models.bucket import Bucket
from openapi_client.models.complaint import Complaint
from openapi_client.models.hit import Hit
from openapi_client.models.hits import Hits
from openapi_client.models.hits_total import HitsTotal
from openapi_client.models.meta import Meta
from openapi_client.models.multi_level_aggregation import MultiLevelAggregation
from openapi_client.models.multi_level_aggregation_field import MultiLevelAggregationField
from openapi_client.models.multi_level_bucket import MultiLevelBucket
from openapi_client.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw
from openapi_client.models.search_result import SearchResult
from openapi_client.models.search_result_aggregations import SearchResultAggregations
from openapi_client.models.states_result import StatesResult
from openapi_client.models.states_result_aggregations import StatesResultAggregations
from openapi_client.models.trends_result import TrendsResult
from openapi_client.models.trends_result_aggregations import TrendsResultAggregations

""",
            name=__name__,
            doc=__doc__,
        )
    )
