# coding: utf-8

# flake8: noqa

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ComplaintsApi",
    "TrendsApi",
    "TypeaheadApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Aggregation",
    "AggregationDate",
    "AggregationField",
    "Bucket",
    "Complaint",
    "Hit",
    "Hits",
    "HitsTotal",
    "Meta",
    "MultiLevelAggregation",
    "MultiLevelAggregationField",
    "MultiLevelBucket",
    "MultiLevelBucketFieldRaw",
    "SearchResult",
    "SearchResultAggregations",
    "StatesResult",
    "StatesResultAggregations",
    "TrendsResult",
    "TrendsResultAggregations",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from ccdb_sdk.api.complaints_api import ComplaintsApi as ComplaintsApi
    from ccdb_sdk.api.trends_api import TrendsApi as TrendsApi
    from ccdb_sdk.api.typeahead_api import TypeaheadApi as TypeaheadApi
    
    # import ApiClient
    from ccdb_sdk.api_response import ApiResponse as ApiResponse
    from ccdb_sdk.api_client import ApiClient as ApiClient
    from ccdb_sdk.configuration import Configuration as Configuration
    from ccdb_sdk.exceptions import OpenApiException as OpenApiException
    from ccdb_sdk.exceptions import ApiTypeError as ApiTypeError
    from ccdb_sdk.exceptions import ApiValueError as ApiValueError
    from ccdb_sdk.exceptions import ApiKeyError as ApiKeyError
    from ccdb_sdk.exceptions import ApiAttributeError as ApiAttributeError
    from ccdb_sdk.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from ccdb_sdk.models.aggregation import Aggregation as Aggregation
    from ccdb_sdk.models.aggregation_date import AggregationDate as AggregationDate
    from ccdb_sdk.models.aggregation_field import AggregationField as AggregationField
    from ccdb_sdk.models.bucket import Bucket as Bucket
    from ccdb_sdk.models.complaint import Complaint as Complaint
    from ccdb_sdk.models.hit import Hit as Hit
    from ccdb_sdk.models.hits import Hits as Hits
    from ccdb_sdk.models.hits_total import HitsTotal as HitsTotal
    from ccdb_sdk.models.meta import Meta as Meta
    from ccdb_sdk.models.multi_level_aggregation import MultiLevelAggregation as MultiLevelAggregation
    from ccdb_sdk.models.multi_level_aggregation_field import MultiLevelAggregationField as MultiLevelAggregationField
    from ccdb_sdk.models.multi_level_bucket import MultiLevelBucket as MultiLevelBucket
    from ccdb_sdk.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw as MultiLevelBucketFieldRaw
    from ccdb_sdk.models.search_result import SearchResult as SearchResult
    from ccdb_sdk.models.search_result_aggregations import SearchResultAggregations as SearchResultAggregations
    from ccdb_sdk.models.states_result import StatesResult as StatesResult
    from ccdb_sdk.models.states_result_aggregations import StatesResultAggregations as StatesResultAggregations
    from ccdb_sdk.models.trends_result import TrendsResult as TrendsResult
    from ccdb_sdk.models.trends_result_aggregations import TrendsResultAggregations as TrendsResultAggregations
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from ccdb_sdk.api.complaints_api import ComplaintsApi as ComplaintsApi
from ccdb_sdk.api.trends_api import TrendsApi as TrendsApi
from ccdb_sdk.api.typeahead_api import TypeaheadApi as TypeaheadApi

# import ApiClient
from ccdb_sdk.api_response import ApiResponse as ApiResponse
from ccdb_sdk.api_client import ApiClient as ApiClient
from ccdb_sdk.configuration import Configuration as Configuration
from ccdb_sdk.exceptions import OpenApiException as OpenApiException
from ccdb_sdk.exceptions import ApiTypeError as ApiTypeError
from ccdb_sdk.exceptions import ApiValueError as ApiValueError
from ccdb_sdk.exceptions import ApiKeyError as ApiKeyError
from ccdb_sdk.exceptions import ApiAttributeError as ApiAttributeError
from ccdb_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from ccdb_sdk.models.aggregation import Aggregation as Aggregation
from ccdb_sdk.models.aggregation_date import AggregationDate as AggregationDate
from ccdb_sdk.models.aggregation_field import AggregationField as AggregationField
from ccdb_sdk.models.bucket import Bucket as Bucket
from ccdb_sdk.models.complaint import Complaint as Complaint
from ccdb_sdk.models.hit import Hit as Hit
from ccdb_sdk.models.hits import Hits as Hits
from ccdb_sdk.models.hits_total import HitsTotal as HitsTotal
from ccdb_sdk.models.meta import Meta as Meta
from ccdb_sdk.models.multi_level_aggregation import MultiLevelAggregation as MultiLevelAggregation
from ccdb_sdk.models.multi_level_aggregation_field import MultiLevelAggregationField as MultiLevelAggregationField
from ccdb_sdk.models.multi_level_bucket import MultiLevelBucket as MultiLevelBucket
from ccdb_sdk.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw as MultiLevelBucketFieldRaw
from ccdb_sdk.models.search_result import SearchResult as SearchResult
from ccdb_sdk.models.search_result_aggregations import SearchResultAggregations as SearchResultAggregations
from ccdb_sdk.models.states_result import StatesResult as StatesResult
from ccdb_sdk.models.states_result_aggregations import StatesResultAggregations as StatesResultAggregations
from ccdb_sdk.models.trends_result import TrendsResult as TrendsResult
from ccdb_sdk.models.trends_result_aggregations import TrendsResultAggregations as TrendsResultAggregations

""",
            name=__name__,
            doc=__doc__,
        )
    )
