# coding: utf-8

# flake8: noqa

"""
    Consumer Complaint Database API

    The API for searching the Consumer Complaint Database

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ComplaintsApi",
    "TrendsApi",
    "TypeaheadApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Aggregation",
    "AggregationDate",
    "AggregationField",
    "Bucket",
    "Complaint",
    "Hit",
    "Hits",
    "HitsTotal",
    "Meta",
    "MultiLevelAggregation",
    "MultiLevelAggregationField",
    "MultiLevelBucket",
    "MultiLevelBucketFieldRaw",
    "SearchResult",
    "SearchResultAggregations",
    "StatesResult",
    "StatesResultAggregations",
    "TrendsResult",
    "TrendsResultAggregations",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from openapi_client.api.complaints_api import ComplaintsApi as ComplaintsApi
    from openapi_client.api.trends_api import TrendsApi as TrendsApi
    from openapi_client.api.typeahead_api import TypeaheadApi as TypeaheadApi
    
    # import ApiClient
    from openapi_client.api_response import ApiResponse as ApiResponse
    from openapi_client.api_client import ApiClient as ApiClient
    from openapi_client.configuration import Configuration as Configuration
    from openapi_client.exceptions import OpenApiException as OpenApiException
    from openapi_client.exceptions import ApiTypeError as ApiTypeError
    from openapi_client.exceptions import ApiValueError as ApiValueError
    from openapi_client.exceptions import ApiKeyError as ApiKeyError
    from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
    from openapi_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from openapi_client.models.aggregation import Aggregation as Aggregation
    from openapi_client.models.aggregation_date import AggregationDate as AggregationDate
    from openapi_client.models.aggregation_field import AggregationField as AggregationField
    from openapi_client.models.bucket import Bucket as Bucket
    from openapi_client.models.complaint import Complaint as Complaint
    from openapi_client.models.hit import Hit as Hit
    from openapi_client.models.hits import Hits as Hits
    from openapi_client.models.hits_total import HitsTotal as HitsTotal
    from openapi_client.models.meta import Meta as Meta
    from openapi_client.models.multi_level_aggregation import MultiLevelAggregation as MultiLevelAggregation
    from openapi_client.models.multi_level_aggregation_field import MultiLevelAggregationField as MultiLevelAggregationField
    from openapi_client.models.multi_level_bucket import MultiLevelBucket as MultiLevelBucket
    from openapi_client.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw as MultiLevelBucketFieldRaw
    from openapi_client.models.search_result import SearchResult as SearchResult
    from openapi_client.models.search_result_aggregations import SearchResultAggregations as SearchResultAggregations
    from openapi_client.models.states_result import StatesResult as StatesResult
    from openapi_client.models.states_result_aggregations import StatesResultAggregations as StatesResultAggregations
    from openapi_client.models.trends_result import TrendsResult as TrendsResult
    from openapi_client.models.trends_result_aggregations import TrendsResultAggregations as TrendsResultAggregations
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from openapi_client.api.complaints_api import ComplaintsApi as ComplaintsApi
from openapi_client.api.trends_api import TrendsApi as TrendsApi
from openapi_client.api.typeahead_api import TypeaheadApi as TypeaheadApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.aggregation import Aggregation as Aggregation
from openapi_client.models.aggregation_date import AggregationDate as AggregationDate
from openapi_client.models.aggregation_field import AggregationField as AggregationField
from openapi_client.models.bucket import Bucket as Bucket
from openapi_client.models.complaint import Complaint as Complaint
from openapi_client.models.hit import Hit as Hit
from openapi_client.models.hits import Hits as Hits
from openapi_client.models.hits_total import HitsTotal as HitsTotal
from openapi_client.models.meta import Meta as Meta
from openapi_client.models.multi_level_aggregation import MultiLevelAggregation as MultiLevelAggregation
from openapi_client.models.multi_level_aggregation_field import MultiLevelAggregationField as MultiLevelAggregationField
from openapi_client.models.multi_level_bucket import MultiLevelBucket as MultiLevelBucket
from openapi_client.models.multi_level_bucket_field_raw import MultiLevelBucketFieldRaw as MultiLevelBucketFieldRaw
from openapi_client.models.search_result import SearchResult as SearchResult
from openapi_client.models.search_result_aggregations import SearchResultAggregations as SearchResultAggregations
from openapi_client.models.states_result import StatesResult as StatesResult
from openapi_client.models.states_result_aggregations import StatesResultAggregations as StatesResultAggregations
from openapi_client.models.trends_result import TrendsResult as TrendsResult
from openapi_client.models.trends_result_aggregations import TrendsResultAggregations as TrendsResultAggregations

""",
            name=__name__,
            doc=__doc__,
        )
    )
